// config.cpp
#include "config.h"

int INITIAL_WAIT = 1000000;
int STATE_GENERAL_DURATION = 50000;
int STATE_FSR_DURATION = 0;
int STATE_IMU_DURATION = 0;
int STATE_RAM_DURATION = 0;
int STATE_BLE_DURATION = 0;
int STATE_ENERGY_DURATION = 0;
int STATE_CUSTOM_DURATION = 0;
int RESOURCE_RTC_DURATION = 100000;
int RAM_BUFFER_RATIO_REFRESH = 10000;
